image: affidaty/rust-buster-builder

stages:
    - lints
    - build
    - test

lints:
    stage: lints
    script:
        - cargo fmt --all -- --check
        - cargo clippy --all -- -D warnings

build:
    stage: build
    dependencies:
        - lints
    script:
        - cargo build

test:
    stage: test
    dependencies:
        - build
    script:
        - cargo test
